---

- hosts: all

  tasks:

    - name: install packages

      become: true

      become_user: root

      dnf:

        state: present

        name:

         - tcsh
         - htop
         - vim 
         - wget 
         - htop 
         - tmux
         - php5.6
         - nginx
